version: '3.4'
services:

  # amAdmin, Password1
  # https://openam.webinar.local:8449/openam/XUI/#login/
  # https://openam.webinar.local:8449/openam/oauth2/webinar/.well-known/openid-configuration
  openamwebinarlocal:
    image: webinar/openam:latest
    container_name: openamwebinarlocal
    hostname: openam.webinar.local
    restart: on-failure
    networks:
      - webinar
    depends_on:
      - dswebinarlocal
    ports:
      - "8449:8449"
    volumes:
      - ./dev/tlskey.p12:/usr/local/tomcat/ssl/tlskey.p12
    environment:
      - "SSL_PWD=${SSL_PWD}"
      - "SSL_PORT=8449"
      - "HOSTNAME=${HOSTNAME_AM}"

  # uid=admin/ Password1
  # no console
  dswebinarlocal:
    image: webinar/ds:latest
    container_name: dswebinarlocal
    hostname: ds.webinar.local
    restart: on-failure
    networks:
      - webinar
    ports:
      - "1636:1636"
      - "1689:1689"
      - "8452:8452"
      - "8989:8989"
      - "4444:4444"
      - "50636:50636"

networks:
  webinar:
    driver: bridge